export interface Project {
    id: string;
    name: string;
    comment: string;
    year: number;
    agency: string;
    figma: string;
    github: string;
    link: string;
    wordpress: boolean;
    photoshop: boolean;
    illustrator: boolean;
    threejs: boolean;
    blender: boolean;
    vuejs: boolean;
    tailwind: boolean;
    netlify: boolean;
    pocketbase: boolean;
    supabase: boolean;
    firebase: boolean;
    image: string;
    imageUrl: string;
};